name: Google Java Format Check

on:
  push:
    branches:
      - '*'  # 모든 브랜치에 push될 때 실행
  pull_request:
    branches:
      - '*'  # 모든 브랜치의 Pull Request가 생성될 때 실행

jobs:
  format_check:
    name: Google Java Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          server-password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build(with Gradle)
        run: | 
          cd ./your-delivery
          ./gradlew build  
          #'./gradlew'는 gradle 스크립트 경로

      - name: Install Google Java Format
        run: |
          cd ./your-delivery
          wget https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar
          mv google-java-format-1.15.0-all-deps.jar google-java-format.jar
          # google java format 공식 사이트 asset 다운로드 경로

      - name: apply Google Java Format
        run: |
          cd ./your-delivery
          chmod +x .
          java -jar google-java-format.jar --dry-run --set-exit-if-changed **/*.jar
          # 하위폴더에 구글 포맷 적용

      - name: Install CheckStyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.2/checkstyle-10.12.2-all.jar
          # 설치 완료

      - name: Check CheckStyle
        run: |
          java -jar checkstyle-10.12.2-all.jar -c /google_checks.xml **/*.java
          # 하위폴더에 구글 포맷 적용되어있는지 확인

      - name: Display Completion Message
        run: echo "Workflow completed successfully!"
